# Generated by Django 3.1.2 on 2020-10-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidyoddha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_otp',
            field=models.PositiveIntegerField(default=123456),
            preserve_default=False,
        ),
    ]
