# Generated by Django 3.1.2 on 2020-10-25 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidyoddha', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_name',
        ),
    ]
