# Generated by Django 3.1.2 on 2020-10-25 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidyoddha', '0003_auto_20201025_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patient',
            new_name='patient_id',
        ),
    ]
