# Generated by Django 3.1.2 on 2020-11-08 06:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('covidyoddha', '0005_patient_patient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='patient',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular patient', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_name',
            field=models.CharField(max_length=100),
        ),
    ]
