# Generated by Django 3.1.2 on 2020-11-08 07:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('covidyoddha', '0006_auto_20201108_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, help_text='Unique ID for this particular patient', primary_key=True, serialize=False),
        ),
    ]
