# Generated by Django 3.1.2 on 2020-11-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidyoddha', '0008_auto_20201108_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(upload_to='report/'),
        ),
    ]
